### ISSUE TITLE
question about Task1,2 

### ISSUE THREAD

**Issue by Mayar2009** [deep-nlp-spring-2020/Task-2-puffofsmoke#6]
Hi!
Why you have hidden=None every time you call validate_on_batch in Task1,2?
I could not get the idea, cause it is already None for every batch ' forward(self, inputs, hidden=None)'
 can you explain, please?

**Comment by puffofsmoke** [comment]
Thank you for the question.

Probably we talking about this lines of code:

```
hidden = None
....
for...
    loss = train_on_batch(model=model, criterion=criterion, x=x, y=y, optimizer=optimizer, hidden=hidden)
```

Yes of course, we can skip any default parameters. Also we can skip arguments names and make code shorter, like this:
```
for...
    loss = train_on_batch(model, criterion, x, y, optimizer)
```
My points are:

- During assignments I act like all code is under active development. Arguments order can be changed at any time, for example. It's good reason to love arguments names time to time.
- I don't want to think or to do any extra activity while reading my code. **While we reading original code we understanding what going on without any knowledge about default parameters in forward method or remembering them.**

One year after no one will remember like we calling function `train_on_batch` which will call function `validate_on_batch` calling method `forward` method who have default parameter `hidden=None` for this model.

Yes, sure, we can investigate it quickly, but, in my experience, code reading is more often activity then code writing and spending some extra time during code writing can save more time for future code reading.

I like to mention also one more things connected not only to coding.

It's "reverse logic mistake".

While we asking this kind of questions we have much more knowledge about situation than person who we ask had.

For example, now we have knowledge how this kind of models should work and can be implemented with pytorch but at the beginning of assignment or during typing that's lines of code i didn't have full picture. It was a lot of trials and fails.

**Comment by vaskonov** [comment]
@Mayar2009 please set the proper grade
